name: Sync CLI Microsoft 365 Docs

on:
  schedule:
    # Run at 00:00 on the first day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GodSpoon/LLM-ReferenceDocs
        uses: actions/checkout@v4
        with:
          path: ./llm-ref-docs

      - name: Checkout pnp/cli-microsoft365
        uses: actions/checkout@v4
        with:
          repository: pnp/cli-microsoft365
          path: ./cli-m365-source

      - name: Prepare target directory
        run: |
          mkdir -p ./llm-ref-docs/cli-microsoft365
          # Clean up previous files if necessary, depending on desired behavior (add/update vs full sync)
          # For a full sync, you might want to remove existing files before copying
          # rm -rf ./llm-ref-docs/cli-microsoft365/*

      - name: Copy required files
        run: |
          SOURCE_DIR="./cli-m365-source/docs/docs"
          TARGET_DIR="./llm-ref-docs/cli-microsoft365"

          # Copy .mdx, .json, and .ps1 files
          find "$SOURCE_DIR" -type f \( -name "*.mdx" -o -name "*.json" -o -name "*.ps1" \) -exec cp {} "$TARGET_DIR/" \;

      - name: Convert .mdx to .md
        run: |
          TARGET_DIR="./llm-ref-docs/cli-microsoft365"
          cd "$TARGET_DIR"
          for file in *.mdx; do
            if [ -f "$file" ]; then # Check if file exists (handles case where no .mdx files are found)
              mv "$file" "${file%.mdx}.md"
            fi
          done

      - name: Commit and push changes
        run: |
          cd ./llm-ref-docs
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add cli-microsoft365
          git status
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m 'Sync CLI Microsoft 365 documentation'
            git push
          else
            echo "No changes to commit."
          fi
